# initializes Postgres databases and Kafka topics

networks:
  branchtalk-monolith:
    driver: bridge

services:
  postgres-setup:
    image: 'postgres:17-alpine'
    command: >
      sh -c "(psql --host postgres --username postgres --command=\"CREATE DATABASE users\" || true) &&
             (psql --host postgres --username postgres --command=\"CREATE USER users WITH PASSWORD 'password'\" users || true) &&
             (psql --host postgres --username postgres --command=\"CREATE SCHEMA users AUTHORIZATION users\" users || true) &&
             (psql --host postgres --username postgres --command=\"CREATE DATABASE discussions\" || true) &&
             (psql --host postgres --username postgres --command=\"CREATE USER discussions WITH PASSWORD 'password'\" discussions || true) &&
             (psql --host postgres --username postgres --command=\"CREATE SCHEMA discussions AUTHORIZATION discussions\" discussions || true) &&
             (psql --host postgres --username postgres --command=\"CREATE DATABASE notifications\" || true) &&
             (psql --host postgres --username postgres --command=\"CREATE USER notifications WITH PASSWORD 'password'\" notifications || true) &&
             (psql --host postgres --username postgres --command=\"CREATE SCHEMA notifications AUTHORIZATION notifications\" notifications || true)"
    environment:
      PGPASSWORD: password # for psql
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - branchtalk-monolith

  kafka-setup:
    image: 'apache/kafka:3.7.0'
    command: >
      sh -c '/opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic users &&
             /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic users-internal &&
             /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic discussions &&
             /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic discussions-internal &&
             /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic notifications &&
             /opt/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9094 --partitions 1 --replication-factor 1 --topic notifications-internal'
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - branchtalk-monolith
